// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBooking.Infrastructure.Data;

#nullable disable

namespace MovieBooking.Infrastructure.Migrations
{
    [DbContext(typeof(MovieBookingDbContext))]
    [Migration("20260328000000_Add_Phim_PosterUrl_TheLoai_XepHang")]
    partial class Add_Phim_PosterUrl_TheLoai_XepHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieBooking.Domain.Entities.DonDatVe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("LichChieuId").HasColumnType("int");
                    b.Property<DateTime?>("NgayCapNhat").HasColumnType("datetime2");
                    b.Property<DateTime>("NgayTao").HasColumnType("datetime2");
                    b.Property<int>("NguoiDungId").HasColumnType("int");
                    b.Property<decimal>("TongTien").HasColumnType("decimal(18, 2)");
                    b.Property<string>("TrangThai").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("LichChieuId");
                    b.HasIndex("NguoiDungId");
                    b.ToTable("DonDatVes");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.Ghe", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("LoaiGhe").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("PhongChieuId").HasColumnType("int");
                    b.Property<string>("SoGhe").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("PhongChieuId");
                    b.ToTable("Ghes");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.KhuyenMai", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("ConHieuLuc").HasColumnType("bit");
                    b.Property<decimal>("GiaTriGiam").HasColumnType("decimal(18, 2)");
                    b.Property<string>("MaKhuyenMai").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("NgayBatDau").HasColumnType("datetime2");
                    b.Property<DateTime?>("NgayCapNhat").HasColumnType("datetime2");
                    b.Property<DateTime>("NgayKetThuc").HasColumnType("datetime2");
                    b.Property<DateTime>("NgayTao").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.LichChieu", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal>("GiaCoBan").HasColumnType("decimal(18, 2)");
                    b.Property<DateTime>("GioBatDau").HasColumnType("datetime2");
                    b.Property<DateTime>("GioKetThuc").HasColumnType("datetime2");
                    b.Property<DateTime?>("NgayCapNhat").HasColumnType("datetime2");
                    b.Property<DateTime>("NgayTao").HasColumnType("datetime2");
                    b.Property<int>("PhimId").HasColumnType("int");
                    b.Property<int>("PhongChieuId").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("PhimId");
                    b.HasIndex("PhongChieuId");
                    b.ToTable("LichChieus");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("HoTen").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("MatKhauHash").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("NgayCapNhat").HasColumnType("datetime2");
                    b.Property<DateTime>("NgayTao").HasColumnType("datetime2");
                    b.Property<string>("VaiTro").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.Phim", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<bool>("DangChieu").HasColumnType("bit");
                    b.Property<string>("DaoDien").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("DienVien").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("MoTa").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("NgayCapNhat").HasColumnType("datetime2");
                    b.Property<DateTime>("NgayTao").HasColumnType("datetime2");
                    b.Property<string>("PosterUrl").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("TenPhim").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("TheLoai").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("ThoiLuong").HasColumnType("int");
                    b.Property<string>("TrailerUrl").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<decimal>("XepHang").HasColumnType("decimal(18,2)");
                    b.HasKey("Id");
                    b.ToTable("Phims");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.PhongChieu", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime?>("NgayCapNhat").HasColumnType("datetime2");
                    b.Property<DateTime>("NgayTao").HasColumnType("datetime2");
                    b.Property<int>("RapId").HasColumnType("int");
                    b.Property<string>("TenPhong").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("RapId");
                    b.ToTable("PhongChieus");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.Rap", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("DiaChi").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Hotline").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("NgayCapNhat").HasColumnType("datetime2");
                    b.Property<DateTime>("NgayTao").HasColumnType("datetime2");
                    b.Property<string>("TenRap").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Raps");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.ThanhToan", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("DonDatVeId").HasColumnType("int");
                    b.Property<string>("MaGiaoDich").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("NgayCapNhat").HasColumnType("datetime2");
                    b.Property<DateTime>("NgayTao").HasColumnType("datetime2");
                    b.Property<string>("PhuongThuc").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<decimal>("SoTien").HasColumnType("decimal(18, 2)");
                    b.Property<string>("TrangThai").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("DonDatVeId").IsUnique();
                    b.ToTable("ThanhToans");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.Ve", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("DonDatVeId").HasColumnType("int");
                    b.Property<int>("GheId").HasColumnType("int");
                    b.Property<decimal>("GiaVe").HasColumnType("decimal(18, 2)");
                    b.HasKey("Id");
                    b.HasIndex("DonDatVeId");
                    b.HasIndex("GheId");
                    b.ToTable("Ves");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.DonDatVe", b =>
                {
                    b.HasOne("MovieBooking.Domain.Entities.LichChieu", "LichChieu").WithMany("DonDatVes").HasForeignKey("LichChieuId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("MovieBooking.Domain.Entities.NguoiDung", "NguoiDung").WithMany("DonDatVes").HasForeignKey("NguoiDungId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("LichChieu");
                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.Ghe", b =>
                {
                    b.HasOne("MovieBooking.Domain.Entities.PhongChieu", "PhongChieu").WithMany("Ghes").HasForeignKey("PhongChieuId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.LichChieu", b =>
                {
                    b.HasOne("MovieBooking.Domain.Entities.Phim", "Phim").WithMany("LichChieus").HasForeignKey("PhimId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("MovieBooking.Domain.Entities.PhongChieu", "PhongChieu").WithMany("LichChieus").HasForeignKey("PhongChieuId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Phim");
                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.PhongChieu", b =>
                {
                    b.HasOne("MovieBooking.Domain.Entities.Rap", "Rap").WithMany("PhongChieus").HasForeignKey("RapId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Rap");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.ThanhToan", b =>
                {
                    b.HasOne("MovieBooking.Domain.Entities.DonDatVe", "DonDatVe").WithOne("ThanhToan").HasForeignKey("MovieBooking.Domain.Entities.ThanhToan", "DonDatVeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("DonDatVe");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.Ve", b =>
                {
                    b.HasOne("MovieBooking.Domain.Entities.DonDatVe", "DonDatVe").WithMany("Ves").HasForeignKey("DonDatVeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("MovieBooking.Domain.Entities.Ghe", "Ghe").WithMany("Ves").HasForeignKey("GheId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("DonDatVe");
                    b.Navigation("Ghe");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.DonDatVe", b =>
                {
                    b.Navigation("ThanhToan").IsRequired();
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("MovieBooking.Domain.Entities.Ghe", b => { b.Navigation("Ves"); });
            modelBuilder.Entity("MovieBooking.Domain.Entities.LichChieu", b => { b.Navigation("DonDatVes"); });
            modelBuilder.Entity("MovieBooking.Domain.Entities.NguoiDung", b => { b.Navigation("DonDatVes"); });
            modelBuilder.Entity("MovieBooking.Domain.Entities.Phim", b => { b.Navigation("LichChieus"); });
            modelBuilder.Entity("MovieBooking.Domain.Entities.PhongChieu", b =>
                {
                    b.Navigation("Ghes");
                    b.Navigation("LichChieus");
                });
            modelBuilder.Entity("MovieBooking.Domain.Entities.Rap", b => { b.Navigation("PhongChieus"); });
#pragma warning restore 612, 618
        }
    }
}
